version: "3.6"

services:
  rasa-server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app

  rasa-actions:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
